Fix error in SysTimeClass::Get
TheAssemblyArmada/Thyme pull request #1105
Opened 2024-02-11 13:18 UTC by xezon

* Split off of #796

This claims to be a fix for a Thyme specific issue.

2024-02-14 22:56 UTC, tomsons26 approved these changes

2024-02-15 03:06 UTC, tomsons26 requested changes
This seems was 
```
int SysTimeClass::Get()
{
#ifdef GAME_DLL
#define _is_init (Make_Global<bool>(0x00A66B30))
#else
    static bool _is_init;
#endif
    if (!_is_init) {
        Reset();
        _is_init = true;
    }

    unsigned time = rts::Get_Time();

    if (time > m_startTime) {
        return time - m_startTime;
    }
    return time + m_negTime;
}
```

2024-02-15 18:17 UTC, xezon commented
Fixed.

2024-02-15 22:05 UTC, tomsons26 approved these changes

2024-02-15 22:37 UTC, merged