Fix map waypoint loading
TheAssemblyArmada/Thyme pull request #1165
Opened 2024-10-27 16:34 UTC by 6emmes

Fixes #1053

2024-10-28 15:37 UTC, tomsons26 requested changes
either g_waypoints or s_waypoints doesn't seem should exist, looks like only g_waypoints should exist

2024-10-28 16:56 UTC, 6emmes commented
@tomsons26 
Hi, thanks for comment.
Yes, those two variable are very confusing but it seems accurate to the source code (for example WaypointMap::Update).

2024-10-29 10:37 UTC, tomsons26 commented
hu my comment edit didn't save..

remove s_waypoints and make
```
#ifndef GAME_DLL
WaypointMap *g_waypoints = nullptr;
MapCache *g_theMapCache = nullptr;
#endif
```
code should be only using g_waypoints, there is no duplicate WaypointMap * global

2024-10-30 18:21 UTC, tomsons26 approved these changes

2024-10-31 07:40 UTC, merged