Image class
TheAssemblyArmada/Thyme pull request #150
Opened 2020-08-30 10:43 UTC by Smileynator

This should be all for the image class. I have found no issues in testing myself.
2 methods are in there, but i have not found their location in the WIN binary. I believe they are properly implemented though.

Sorry about clang there, seems it got upset with my latest changes to Urf8String and decided to do something about that just now. Not sure how or when that is supposed to happen but it looks like it is pure formatting either way. I have not applied any changes to the file myself.

2020-08-31 21:30 UTC, OmniBlade requested changes
Just a few minor style fixes to do, plus if you want to do the simplified bitwise assignments.

2020-08-31 21:30 UTC, OmniBlade commented on src/CMakeLists.txt
> +	game/client/image.cpp
Tab rather than spaces here? Clang format doesn't handle the cmake I don't believe.

2020-08-31 21:30 UTC, OmniBlade commented on src/game/client/image.cpp
> +    m_status = m_status | bit;
can simplify this to `m_status |= bit;`

2020-08-31 21:30 UTC, OmniBlade commented on src/game/client/image.cpp
> +    m_status = m_status & ~bit;
Can simplify to `m_status &= ~bit;`

2020-08-31 21:30 UTC, OmniBlade commented on src/game/client/image.h
> +};
Missing newline at end of file.

2020-09-01 11:24 UTC, tomsons26 commented on src/game/client/image.cpp
> +    m_UVCoords.hi.x = 1.0;
should be setting y here

2020-09-01 11:25 UTC, tomsons26 commented on src/game/client/image.cpp
> +const char *imageStatusNames[3] = {"ROTATED_90_CLOCKWISE", "RAW_TEXTURE", nullptr};
was likely a static in the function that uses it, also s_imageStatusNames if you make a global, _imageStatusNames if you put it in the function

2020-09-01 11:27 UTC, tomsons26 commented on src/game/client/image.cpp
> +    if (byte != 0) {
isn't correct, it checks a bit here, its checking for ROTATED_90_CLOCKWISE

2020-09-01 11:29 UTC, tomsons26 commented on src/game/client/image.h
> +    static void Parse_Image_Coords(INI *ini, void *formal, void *store, const void *user_data);
formal is what MSVC uses when there's no name, the actual name for these is instance

2020-09-01 20:07 UTC, Smileynator commented
All issues should be resolved as suggested or discussed.

2020-09-02 21:14 UTC, OmniBlade approved these changes

2020-09-02 21:17 UTC, merged