Implements W3DMouse
TheAssemblyArmada/Thyme pull request #172
Opened 2020-11-02 19:52 UTC by duncanspumpkin

Following on from #169. This is the W3DMouse.
The main mouse creation function has been hooked so all code written is operational.

2020-11-04 08:02 UTC, duncanspumpkin commented
I don't have anything else to add to this PR atm as need other classes done. Think its ready for review.

2020-11-04 23:03 UTC, OmniBlade requested changes

2020-11-04 23:03 UTC, OmniBlade commented on src/hooker/setuphooks_zh.cpp
> +    Hook_Method(0x0073C170, &Win32Mouse::Add_Win32_Event);
Duplicate hook?

2020-11-04 23:03 UTC, OmniBlade commented on src/platform/w3dengine/client/w3dmouse.h
> +Win32Mouse *Create_Mouse();
Missing new line, clang format doesn't catch these unfortunately.

2020-11-05 22:51 UTC, OmniBlade approved these changes

2020-11-06 22:09 UTC, merged