W3dassetmgr
TheAssemblyArmada/Thyme pull request #185
Opened 2020-11-08 12:23 UTC by duncanspumpkin

WiP. Continuation from W3DDisplay.

2020-11-22 09:43 UTC, duncanspumpkin commented on src/platform/w3dengine/client/w3ddisplay.h
> +    static GameAssetManager *&s_assetManager; // TODO: Actual type is GameAssetManager
Remove TODO message

2020-11-22 09:44 UTC, duncanspumpkin commented on src/w3d/renderer/assetmgr.h
>  class W3DAssetManager
Add note that `W3DAssetManager` is the renamed `WW3DAssetManager`

2021-10-15 13:30 UTC, OmniBlade requested changes
Looks like some stray local notes seeped into the PR?

2021-10-15 13:30 UTC, OmniBlade commented on src/game/common/system/asciistring.h
> +// Windows to POSIX names
This change probably shouldn't be part of the PR I'm guessing?

2021-10-15 14:33 UTC, duncanspumpkin commented on src/game/common/system/asciistring.h
> +// Windows to POSIX names
I mentioned this a long time ago it's something that would be useful to have documented somewhere in the codebase so doing a search for either will hit these.

2021-10-15 19:43 UTC, tomsons26 commented on src/w3d/renderer/assetmgr.cpp
> +    Release_All_FontChars();
should have a commented out line for Release_All_Font3DDatas call to keep a record that this was here

2021-10-15 19:44 UTC, tomsons26 commented on src/w3d/renderer/assetmgr.cpp
> +                for (auto i = 0; i < m_prototypeLoaders.Count(); ++i) {
this is actually 3 inlines, Load_Prototype that calls Find_Prototype_Loader, Add_Prototype

2021-10-15 19:46 UTC, tomsons26 commented on src/w3d/renderer/assetmgr.cpp
> +    delete[] m_prototypeHashTable;
Add comment that FontCharsList and Font3DDatas were deleted here

2021-10-15 19:50 UTC, tomsons26 commented on src/w3d/renderer/assetmgr.cpp
> +bool W3DAssetManager::Render_Obj_Exists(const char *name)
this is return WW3DAssetManager::Find_Prototype(this, Str1) != 0;

2021-10-16 07:47 UTC, duncanspumpkin commented on src/w3d/renderer/assetmgr.cpp
> +    delete[] m_prototypeHashTable;
FontCharsList destruction is called from its destructor. Likewise Font3DDatas would have been called from its destructor if it was implemented. I can add a comment for the Font3DDatas if you want but I dont think FontCharsList makes sense.

2021-10-16 07:56 UTC, duncanspumpkin commented
Okay thats most of your comments addressed. I'm not 100% sure how those inlined functions are meant to work having looked at only the game.dat.

2021-10-17 17:52 UTC, tomsons26 commented on src/w3d/renderer/assetmgr.h
> +    virtual void Release_Unused_Assets() { Release_Unused_Textures(); }
note that this called Release_Unused_Font3DDatas

2021-10-18 18:55 UTC, tomsons26 approved these changes
Nothing blows up, no actually missing assets. 👍

2021-10-18 21:28 UTC, OmniBlade approved these changes

2021-10-18 21:36 UTC, merged