Fixes various issues in Keyboard class.
TheAssemblyArmada/Thyme pull request #216
Opened 2020-12-07 00:10 UTC by tomsons26

2020-12-07 08:05 UTC, duncanspumpkin commented on src/game/client/input/keyboard.cpp
> +        while (ptr->key != 0) {
You should keep this as a for loop keyboard ptr is never used outside of this loop. I'd suggest changing the name to `keyIO` or something more descriptive.

2020-12-07 08:11 UTC, duncanspumpkin commented on src/game/client/input/keyboard.cpp
> +    return m_modifiers & MODIFIER_LSHIFT || m_modifiers & MODIFIER_RSHIFT || m_modifiers & MODIFIER_SHIFTEX;
I always find it best to add brackets to these to prevent any issues with operator precedence. In this instance there is no issues though.

2020-12-07 08:13 UTC, duncanspumpkin commented on src/game/client/input/keyboard.cpp
> +    if (key > 255) {
`>= KEY_COUNT`

2021-02-18 10:39 UTC, OmniBlade commented
I'm willing to approve this once @duncanspumpkin suggestions are addressed.

2021-03-15 15:20 UTC, OmniBlade requested changes

2021-03-15 15:20 UTC, OmniBlade commented on src/game/client/input/keyboard.cpp
> +        while (ptr->key != 0) {
I agree with @duncanspumpkin on this one, it would be much better as a for loop.
`for (KeyboarIO *keyio = Get_First_Key; keyio->key != 0; ++keyio)`

2021-03-15 15:20 UTC, OmniBlade commented on src/game/client/input/keyboard.cpp
> +                    captainslog_debug("Unable to append key down message to stream");
These debug logs look like they should be debug asserts instead.

2021-03-15 15:20 UTC, OmniBlade commented on src/game/client/input/keyboard.cpp
> +    if (key > 255) {
@duncanspumpkin is right, use the constant we already defined, `>= 256` is the same as `> 255` logically.

2021-03-30 08:48 UTC, OmniBlade approved these changes

2021-03-30 08:48 UTC, merged