FXListStore
TheAssemblyArmada/Thyme pull request #307
Opened 2021-10-25 07:06 UTC by duncanspumpkin

Implemented as far as possible.

2021-10-25 07:20 UTC, duncanspumpkin commented
Copy https://github.com/TheAssemblyArmada/Thyme/blob/2f8051f277d4e890b77aa9a647ec00495a6fdea3/src/game/common/audio/audiomanager.h#L64 for hashmap

2021-10-26 21:52 UTC, xezon commented on src/game/rtsutils.h
>      bool operator()(const T &left, const T &right) const { return (left.Compare(right) == 0); }
To me it looks like this should be the specialized one, and the one below for `int32_t` should be the default. Then you can also remove the specialization from the other file and just have it here in rtsutils.h

2021-10-27 04:45 UTC, duncanspumpkin commented on src/game/rtsutils.h
>      bool operator()(const T &left, const T &right) const { return (left.Compare(right) == 0); }
Yeah it's hard to tell without every consumer implemented. I think this is just a utf8 specialisation rather than a T generic version.

2021-10-27 06:39 UTC, xezon commented on src/game/rtsutils.h
>      bool operator()(const T &left, const T &right) const { return (left.Compare(right) == 0); }
Yep. In std its also a `==` by default. See:
https://en.cppreference.com/w/cpp/utility/functional/equal_to

2022-01-12 20:17 UTC, jonwil requested changes

2022-01-12 20:17 UTC, jonwil commented on src/game/client/fxlist.h
> +    virtual void PostProcessLoad() override {}
This class doesn't override PostProcessLoad.

2022-01-12 20:17 UTC, jonwil commented on src/game/client/fxlist.cpp
> +void FXList::Parse(INI *ini, void *, void *store, const void *)
This already exists as INI::Parse_FX_List. Remove the INI function and replace its use with this one.

2022-01-13 08:01 UTC, jonwil approved these changes
Looks good now, approved.

2022-01-13 08:11 UTC, merged