Implement LoadScreen as far as possible
TheAssemblyArmada/Thyme pull request #460
Opened 2022-01-04 16:20 UTC by duncanspumpkin

Annoyingly barely any of this can be done due to missing `GameWindowManager`

2022-01-04 22:21 UTC, jonwil requested changes
Fix that one address and I will approve this.

2022-01-04 22:21 UTC, jonwil commented on src/game/client/gui/loadscreen.cpp
> +    Call_Method<void, LoadScreen>(PICK_ADDRESS(0x00608620, 0x009C3F31), this);
WB address seems to be 0x009C3F11 and not 0x009C3F31

2022-01-06 12:57 UTC, tomsons26 commented on src/game/client/gui/loadscreen.h
> +    LoadScreen() : m_loadScreen(nullptr) {}
ctor before dtor

2022-01-10 22:25 UTC, jonwil approved these changes
Looks good to me now, approved.

2022-01-11 12:56 UTC, merged