Improve game memory pool setup
TheAssemblyArmada/Thyme pull request #465
Opened 2022-01-06 21:35 UTC by xezon

This change does 2 things:

1. Pool object can now be created with new operator. Calling NEW_POOL_OBJ is no longer necessary.
2. delete MyPoolObject no longer compiles. This is good, because this way compiler prevents misuse.

The reason delete operator cannot be used with this setup, is the fact that the virtual table is deleted before code in delete function is run. Therefore virtual function to access Memory Pool cannot be called anymore.

Therefore only `Delete_Instance` should be called.

An `operator delete` still needs to be there because `operator new` requires the pairing. But given the `MagicEnum`, no one practically calls it by mistake.

2022-01-06 21:37 UTC, xezon commented on src/game/common/system/mempoolobj.h
> +    void *operator new(size_t size, classname##MagicEnum = classname##_GLUE_NOT_IMPLEMENTED) \
`MagicEnum` argument now has default value here. This allows writing `new MyPoolObject`.

2022-01-06 21:38 UTC, xezon commented on src/game/common/system/mempoolobj.h
> -    void operator delete(void *ptr) { captainslog_debug("this should be impossible to call (abstract base class)"); } \
I have seen this error message in the decompile, but it's useless to keep. Best to just delete the function and let the compiler give an error straight.

2022-01-06 21:41 UTC, xezon commented on src/game/common/system/mempoolobj.h
> +        captainslog_dbgassert(0, "Please call Delete_Instance instead of delete."); \
I promoted this to an `assert`, because really it should be treated as an error.

2022-01-06 23:28 UTC, xezon commented
Somehow there is compile error in `ClientUpdateModule` now. Needs figuring out.

2022-01-07 23:44 UTC, OmniBlade approved these changes

2022-01-08 01:42 UTC, tomsons26 requested changes

2022-01-08 01:42 UTC, tomsons26 commented on src/game/logic/object/update/clientupdatemodule.h
> +    IMPLEMENT_ABSTRACT_POOL(ClientUpdateModule)
seems it was DrawableModule that had the pool

2022-01-08 01:47 UTC, tomsons26 approved these changes

2022-01-08 01:51 UTC, merged