Minor tweaks in ThingFactory and ModuleFactory classes
TheAssemblyArmada/Thyme pull request #471
Opened 2022-01-07 22:28 UTC by xezon

A few tweaks.

2022-01-07 22:30 UTC, xezon commented on src/game/common/modules/modulefactory.cpp
> +    captainslog_dbgassert(0, "Module name '%s' not found", name.Str());
I saw this in one of the binaries.

2022-01-07 22:30 UTC, xezon commented on src/game/common/thing/thingfactory.cpp
> +    captainslog_dbgassert(m_nextTemplateID != 0, "m_nextTemplateID wrapped to zero");
Condition can be part of assert itself.

2022-01-07 22:30 UTC, xezon commented on src/game/common/thing/thingfactory.cpp
> +    ThingTemplate *override_template = static_cast<ThingTemplate *>(thing_template->Friend_Get_Final_Override());
Looks like it was `Friend_Get_Final_Override`, which is same as `Get_Final_Override` though. But it allows for `static_cast` here, which is nicer.

2022-01-07 22:30 UTC, xezon commented on src/game/common/thing/thingfactory.cpp
> +        ThingTemplate *that = g_theThingFactory->Find_Template_Internal(reskin_from, true);
Non-World Builder shows `Find_Template_Internal` here, which looks more logical too.

2022-01-07 23:02 UTC, jonwil requested changes
Other than the Find_Template thing, this looks good to me.

2022-01-07 23:02 UTC, jonwil commented on src/game/common/thing/thingfactory.cpp
> +        ThingTemplate *that = g_theThingFactory->Find_Template_Internal(reskin_from, true);
WorldBuilder confirms the original code used Find_Template. Find_Template just happens to be inlined into the other binaries.

2022-01-07 23:21 UTC, xezon commented on src/game/common/thing/thingfactory.cpp
> +        ThingTemplate *that = g_theThingFactory->Find_Template_Internal(reskin_from, true);
reverted.

2022-01-07 23:28 UTC, jonwil approved these changes
Looks good to me now. Approved.

2022-01-08 01:37 UTC, tomsons26 approved these changes

2022-01-08 02:07 UTC, merged