Fix flashbang issue caused by incorrect Map comparator
TheAssemblyArmada/Thyme pull request #492
Opened 2022-01-10 23:08 UTC by duncanspumpkin

2022-01-10 23:11 UTC, jonwil requested changes

2022-01-10 23:11 UTC, jonwil commented on src/game/common/sparsematchfinder.h
> +        bool operator()(const Key &left, const Key &right) const { return left != right; }
This is not correct, we should implement this the way the original did it (see function 006F1520 in ZH worldbuilder) to avoid any risk of bugs.

2022-01-11 08:00 UTC, duncanspumpkin commented on src/game/common/sparsematchfinder.h
> +                if ((left_bit && right_bit) || (!left_bit && !right_bit)) {
This could be simplified to `!(left_bit ^ right_bit)`

2022-01-11 08:19 UTC, xezon commented
Fixes #482

2022-01-11 08:43 UTC, jonwil approved these changes
Looks good now, approved.

2022-01-11 08:43 UTC, merged