Fix housecolor crash and improve readability of relevant code in GameAssetManager
TheAssemblyArmada/Thyme pull request #500
Opened 2022-01-13 21:55 UTC by xezon

Loading **Tournament Desert** map crashes the game.

2022-01-13 22:31 UTC, duncanspumpkin requested changes
Can you just change the nullptr check to the correct way round it would be much cleaner.

2022-01-13 22:31 UTC, duncanspumpkin commented on src/w3d/renderer/assetmgr.cpp
> +            if (strncasecmp(matinfo->Peek_Texture(i)->Get_Name(), "ZHC", 3) == 0) {
unrelated revert

2022-01-13 22:31 UTC, duncanspumpkin commented on src/w3d/renderer/assetmgr.cpp
> +        if (strncasecmp(word, "HOUSECOLOR", 10) == 0) {
unrelated revert

2022-01-13 22:32 UTC, duncanspumpkin commented on src/w3d/renderer/assetmgr.cpp
> +        if (strncasecmp(texture->Get_Name(), "ZHC", 3) == 0) {
revert

2022-01-14 08:09 UTC, xezon commented
I updated the title of the change. That should do (Squash and merge). No need to revert it all.

2022-01-14 08:09 UTC, xezon commented on src/w3d/renderer/assetmgr.cpp
> +        if (strncasecmp(texture->Get_Name(), "ZHC", 3) == 0) {
fixed.

2022-01-14 08:15 UTC, duncanspumpkin approved these changes
I personally dont see this as more readable but its fine.

2022-01-14 08:25 UTC, xezon commented
On second look, it looks as if the `if (word != nullptr)` branch could be removed, no? At this point word is not to be expected null.

2022-01-14 08:58 UTC, duncanspumpkin commented
It can only be nullptr if get name is nullptr. I don't really want to think through all possibilities

2022-01-14 09:06 UTC, xezon commented
If `Get_Name()` was null, then it would crash 2 lines before already at `strchr(mesh->Get_Name(), '.');`. That's why I placed the assert just before that.

2022-01-14 09:12 UTC, duncanspumpkin commented
I don't think it is guaranteed to crash in that function standard doesn't specify if strchr is nullptr safe.

2022-01-14 10:13 UTC, xezon commented
I check later. If `strchr` was checking null, then the `assert` would be obsolete. If `strchr` is not checking null, then the assert is ok and the condition is obsolete.

2022-01-14 18:15 UTC, xezon commented on src/w3d/renderer/assetmgr.cpp
> +            if (strncasecmp(matinfo->Peek_Texture(i)->Get_Name(), "ZHC", 3) == 0) {
reverted

2022-01-14 18:32 UTC, merged