Fix CI warnings
TheAssemblyArmada/Thyme pull request #802
Opened 2022-11-23 10:00 UTC by feliwir

Need to use the latest checkout action version, since old NodeJS actions will be removed

2022-11-23 10:22 UTC, feliwir commented
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

2024-02-05 13:20 UTC, OmniBlade reviewed
This looks fine to me, but given the time that has passed I'd like to rebase it on the latest develop and retest to make sure there is nothing else that needs a version bump.

2024-02-05 13:53 UTC, janisozaur requested changes

2024-02-05 13:53 UTC, janisozaur commented on .github/workflows/linux.yml
> +      - uses: actions/checkout@v3
You need v4 by now.

```suggestion
      - uses: actions/checkout@v4
```

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

2024-02-05 13:53 UTC, janisozaur commented on .github/workflows/windows.yml
> +    - uses: actions/checkout@v3
```suggestion
    - uses: actions/checkout@v4
```

2024-02-05 15:44 UTC, OmniBlade approved these changes

2024-02-05 15:45 UTC, merged